name: Refresh vocabulary tables

on:
#  schedule:
##    - cron: '0 0 * * 0'  # weekly, sunday 12am
#    - cron: '0 8 * * *'  # every day 6am GMT (3/4am EST/EDT)
  workflow_dispatch:
jobs:
  refresh-vocab-tables:
    runs-on: BIDS-Premium-Action-Runners
#    runs-on: ubuntu-latest
    # fail-fast: At least shows "Error: Process completed with exit code 143." instead of "exit code 1", for slightly more information about unexpected exits: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#handling-failures
    strategy:
      fail-fast: false
    steps:
      # Set up
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Print commit hash & branch for rollbacks & troubleshooting
        run: |
          echo "Commit hash: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"
      - name: 'Create env file'
        run: |
          mkdir env
          echo "${{ secrets.ENV_FILE }}" > env/.env
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install --upgrade setuptools
          pip install -r requirements.txt

      # Refresh
      - name: Refresh vocab
        run: make refresh-vocab

      # Test
      - name: Test
        run: python -m unittest test.test_backend.db.test_refresh_dataset_group_tables.TestCurrentDatasetGroupSetup.test_current_vocab
