name: Resolve fetch failures for excess items or members
# todo: rename to _items_members (it fetches excess caes of both)

on:
#  schedule:
#    - cron: '*/20 * * * *'  # every 20 minutes
  workflow_dispatch:
  repository_dispatch:
    types: [resolve-fetch-failures-excess-items]
jobs:
  resolve-fetch-failures-excess-items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Print commit hash & branch for rollbacks & troubleshooting
        run: |
          echo "Commit hash: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"

      - name: 'Create env file'
        run: |
          mkdir env
          echo "${{ secrets.ENV_FILE }}" > env/.env

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          # Reactivate install upgrades of pip, wheel, &/or setuptools if needed
          # python -m pip install --upgrade pip
          # pip install --upgrade wheel
          # pip install --upgrade setuptools
          pip install -r requirements.txt
          TOKEN=$(grep '^PALANTIR_ENCLAVE_AUTHENTICATION_BEARER_TOKEN=' env/.env | cut -d'=' -f2)
          python3 -m pip install vshub_sdk --upgrade --extra-index-url "https://:${TOKEN}@unite.nih.gov/artifacts/api/repositories/ri.artifacts.main.repository.9bc9cc56-4b8c-4560-9bfb-fba8ade55246/contents/release/pypi/simple" --extra-index-url "https://:${TOKEN}@unite.nih.gov/artifacts/api/repositories/ri.foundry-sdk-asset-bundle.main.artifacts.repository/contents/release/pypi/simple"

      - name: Resolve fetch failures
        run: |
          python backend/db/resolve_fetch_failures_excess_items.py
