name: Test - Frontend - Unit tests and QC
on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
        cache-dependency-path: 'frontend/yarn.lock'

    - name: Install dependencies
      working-directory: frontend
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        yarn install --frozen-lockfile

    - name: Run tests
      run: make test-frontend-unit
