# TODO: get to run in GH action (right now times out), then reactivate "on"
# TODO: (a) start backend within GH action, or (b) use dev's backend URL (won't always work)
name: Tests and QC - Frontend
#on:
#  push:
#    branches: [ main, develop ]
#  pull_request:
#    branches: [ main, develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    # TODO: figure out: is it possible just to cd frontend once?
#    - name: cd
#      run: cd frontend
    - name: Install dependencies
      run: cd frontend && npm ci
    - name: Install Playwright Browsers
      run: cd frontend && npx playwright install --with-deps
    - name: Run Playwright tests
      run: cd frontend && npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
